allowBuilds:
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
  esbuild: true
  simple-git-hooks: true
  skia-canvas: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - electron
  - electron-winstaller
  - esbuild
  - simple-git-hooks
  - skia-canvas
  - vue-demi

# 发布 7 天后的包
# minimumReleaseAge: 10080
blockExoticSubdeps: false
nodeLinker: hoisted
