name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*' # 只在版本标签推送时触发

jobs:
  build:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Set Up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.10.0'

      - name: Git SSH fix
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://
      
      - name: Install pnpm 
        uses: pnpm/action-setup@v6
        with: 
          cache: true

      - name: Install Dependencies
        run: pnpm install

      - name: Install Dependencies
        run: pnpm i

      - name: Build Web
        run: pnpm run build:web

      - name: Build Electron App
        run: pnpm run build

      - name: Publish 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm run publish
